[package]
name = "no_stream"
version = "0.1.0"
authors = ["Arnaud"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
csv = "1.1.5"
hyper = "0.14.2"
log = "0.4.14"
